Repository questdb/questdb.io, pull requests merged in 2022-05, with the labels that each got.

#772 feat: document geohash support in CSV import
  docs/concept/geohashes.md
Labels: documentation, enhancement

#770 feat: add OS error codes page
  docs/introduction.md
  docs/troubleshooting/faq.md
  docs/troubleshooting/os-error-codes.md
  netlify.toml
  sidebars.js
Labels: documentation, enhancement

#827 docs: Described 'config.validation.strict' setting.
  docs/reference/configuration.md
Labels: upcoming changes

#835 update docs for standard deviation aggregate function (stddev_samp)
  docs/reference/function/aggregation.md
Labels: documentation, enhancement

#841 Add microsecond as a unit in the description of sample by
  docs/reference/sql/sample-by.md
Labels: enhancement

#860 chore(blog): add parallel SQL filters blog post
  blog/2022-05-26-multi-threaded-sql-filters.md
  static/img/blog/2022-05-26/banner.png
  static/img/blog/2022-05-26/before-and-after-cold-runs.png
  static/img/blog/2022-05-26/before-and-after-hot-runs.png
  static/img/blog/2022-05-26/filter-benchmark.png
  static/img/blog/2022-05-26/filter-with-limit-benchmark.png
  static/img/blog/2022-05-26/how-filtering-works.png
  static/img/blog/2022-05-26/storage-format.png
Labels: enhancement

#849 Prometheus documentation for write amplification metrics, i.e. physically_written_rows.
  docs/third-party-tools/prometheus.md
Labels: upcoming changes
