Repository questdb/questdb.io, pull requests merged in 2022-08, with the labels that each got.

#978 chore (docs) minor editing for docker start guide
  docs/get-started/docker.md
Labels: bug, docs

#979 chore(doc): improve Guides sidebar section
  docs/guides/importing-data-rest.md
  docs/guides/importing-data.md
  sidebars.js
Labels: improvement, Documentation

#984 chore(docs): Adding Docker configs
  docs/guides/importing-data.md
  docs/reference/configuration.md
Labels: improvement, Documentation

#987 chore(docs): actualize thread pool size descriptions
  docs/operations/capacity-planning.md
  docs/reference/configuration.md
Labels: Documentation

#877 chore(docs): document PG Wire read-only mode prop
  docs/reference/configuration.md
Labels: docs

#973 fix: amending supported datatype to first and last #964
  docs/reference/function/aggregation.md
Labels: bug, docs, Documentation

#1004 chore(docs): document new types in count_distinct()
  docs/reference/function/aggregation.md
Labels: Documentation

#1006 chore(docs): commit lag unit
  docs/guides/out-of-order-commit-lag.md
Labels: docs

#1007 chore(docs): fix typo in vacuum table reference
  docs/reference/sql/vacuum-table.md
Labels: Documentation

#1017 chore(docs): symbol, index, SQL refs clarification (#988)
  docs/concept/symbol.md
  docs/reference/sql/alter-table-alter-column-add-index.md
  docs/reference/sql/create-table.md
  static/img/docs/diagrams/.railroad
  static/img/docs/diagrams/columnTypeDef.svg
  static/img/docs/diagrams/createTable.svg
  static/img/docs/diagrams/indexCapacityDef.svg
  static/img/docs/diagrams/indexDef.svg
  static/img/docs/diagrams/inlineIndexDef.svg
Labels: improvement, Documentation
