Repository questdb/questdb.io, pull requests merged in 2023-02, with the labels that each got.

#1321 chore(docs): adding read-only partitions behaviours
  docs/reference/sql/alter-table-attach-partition.md
  docs/reference/sql/insert.md
  docs/reference/sql/update.md
Labels: New feature

#1221 feat(docs) `WAL` documentation
  .gitignore
  docs/concept/geohashes.md
  docs/concept/root-directory-structure.md
  docs/concept/write-ahead-log.md
  docs/introduction.md
  docs/reference/api/java-embedded.md
  docs/reference/configuration.md
  docs/reference/function/meta.md
  docs/reference/sql/alter-table-resume-wal.md
  docs/reference/sql/alter-table-set-type.md
  docs/reference/sql/create-table.md
  sidebars.js
  src/assets/img/camera.svg
  static/img/docs/concepts/wal_process.png
  static/img/docs/concepts/wal_sequencer.png
  static/img/docs/diagrams/.railroad
  static/img/docs/diagrams/alterTable.svg
  static/img/docs/diagrams/alterTableResumeWal.svg
  static/img/docs/diagrams/createTable.svg
  static/img/docs/diagrams/setType.svg
Labels: upcoming changes, New feature

#1341 feat(docs) adding CREATE TABLE IN VOLUME docs
  docs/concept/write-ahead-log.md
  docs/reference/configuration.md
  docs/reference/function/meta.md
  docs/reference/sql/create-table.md
  docs/reference/sql/drop.md
  static/img/docs/diagrams/.railroad
  static/img/docs/diagrams/createTable.svg
  static/img/docs/diagrams/createTableLike.svg
  static/img/docs/diagrams/tableTargetVolumeDef.svg
  static/img/docs/diagrams/test
Labels: upcoming changes

#1393 chore(docs): rename property to cairo.volumes
  docs/reference/configuration.md
  docs/reference/sql/create-table.md
Labels: docs

#1415 chore(docs): fix embedded API snippets
  docs/concept/geohashes.md
  docs/reference/api/java-embedded.md
Labels: bug, docs
