Repository questdb/questdb.io, pull requests merged in 2023-01, with the labels that each got.

#1306 feat(docs) uuid type documented
  docs/reference/sql/datatypes.md
Labels: do not merge, New feature

#1280 chore(docs): added explain description
  docs/introduction.md
  docs/reference/sql/explain.md
  sidebars.js
  static/img/docs/diagrams/.railroad
  static/img/docs/diagrams/explain.svg
Labels: New feature

#1245 feat(sql): added documentation for trigonometric functions sin, cos, tan, cot, asin, acos, atan, atan2, radians, degrees, pi
  docs/introduction.md
  docs/reference/function/trigonometric.md
  sidebars.js
  static/img/docs/atan2.svg
Labels: New feature

#1254 chore(docs) JOIN and ON clause
  docs/reference/sql/join.md
  docs/reference/sql/select.md
  src/assets/img/pages/index/sliceTime.svg
  static/img/docs/diagrams/.railroad
  static/img/docs/diagrams/AsofLtSpliceJoin.svg
  static/img/docs/diagrams/InnerLeftJoin.svg
  static/img/docs/diagrams/crossJoin.svg
  static/img/docs/diagrams/join.svg
  static/img/docs/diagrams/joinOverview.svg
Labels: upcoming changes

#1331 chore(docs): update rolling log writer config sample
  docs/reference/configuration.md
Labels: docs
